# App details (name & description)
name: restaurant_recommendation_app
description: A restaurant recommendation application for end users

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'github.com'

# GitHub
repository: "https://github.com/Quabynah-Codelabs/short-course-flutter-oct-2020"

# Authors
authors:
  - "Quabynah Bilson Jr. <codelbas.quabynah@gmail.com>"

# Versioning
version: 0.0.1+1

# Dart SDK
environment:
  sdk: ">=2.7.0 <3.0.0"

# Packages to be used
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  moor:
  google_fonts:
  flutter_icons:
  shared_preferences:
  provider:
  google_maps_flutter:
  geolocator:
  share:
  flutter_rating_bar:
  flutter_spinkit:
  url_launcher:
  flutter_svg_provider:
  auto_route: ^0.6.7
  get_it: ^4.0.4
  google_sign_in: ^4.5.1
  sliding_sheet: ^0.3.3
  path: ^1.7.0
  path_provider: ^1.6.8
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  moor_generator:
  flutter_launcher_icons:
  auto_route_generator:
  json_serializable:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
#    - assets/svgs/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg