name: restaurant_recommendation_app
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  # json annotation for dart code generation
  json_annotation: ^3.1.0
  # helps us to make calls to the Google Places API service
  http: ^0.12.2
  # user's current location
  geolocator: ^6.1.6
  # google maps for flutter
  google_maps_flutter: ^1.0.6
  # google fonts package
  google_fonts: ^1.1.1
  # flutter icons package
  flutter_icons: ^1.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  # code generator for dart
  build_runner: ^1.10.4
  # serializer
  json_serializable: ^3.5.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/